name = "Stormsurge"
author = "EcoBuilder13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb92fc6ca4ad140f5845e7947f51730b9203d8f02bbf925e7865a53b67f420d1"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
