name = "Stormsurge"
author = "EcoBuilder13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68abaf4c8720d0a78f65d1c13a7503e72ab34d43070f490eddf885fd7f09ca71"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
