name = "Stormsurge"
author = "EcoBuilder13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5783b59ec0f4f546dd1a7d34add11dd70cc218b10cb244c76614ada3331e5da3"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
