name = "Stormsurge"
author = "EcoBuilder13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "605c88c0c5b8f218f5462ef96b750b385690ec8bf253a4daf576bc46436e4d79"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
