name = "Stormsurge"
author = "EcoBuilder13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53cdcf7a49a5849b658ceab30a7f72879eb92d834e51c13251a5112cebce5de8"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
